// Generated by Selenium IDE with screenshots added
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs').promises;   // for writing files
const path = require('path');

describe('yesttt', function() {
  this.timeout(30000)
  let driver
  let vars

  // helper function to save screenshot with a filename
  async function saveScreenshot(driver, filename) {
    let image = await driver.takeScreenshot()
    await fs.writeFile(path.join(__dirname, filename), image, 'base64')
  }

  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })

  afterEach(async function() {
    await driver.quit()
  })

  it('yesttt', async function() {
    await driver.get("https://theysaidso.com/")
    await driver.manage().window().setRect({ width: 1054, height: 800 })

    // Take screenshot after page load
    await saveScreenshot(driver, 'screenshot_01_homepage.png')

    await driver.executeScript("window.scrollTo(0,512)")

    // Take screenshot after scrolling
    await saveScreenshot(driver, 'screenshot_02_after_scroll.png')

    await driver.close()
  })
})
