// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('yesttt', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('yesttt', async function() {
    await driver.get("https://theysaidso.com/")
    await driver.manage().window().setRect({ width: 1054, height: 800 })
    await driver.executeScript("window.scrollTo(0,512)")
    await driver.close()
  })
})
